version: '3.8'

services:
  rag-api:
    build: .
    container_name: rag_api_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    networks:
      - mortgage_ai_network
    restart: unless-stopped

networks:
  mortgage_ai_network:
    external: true
    name: mortgage_ai_network
